// Code generated by scripts/build-go-bindings.mjs. DO NOT EDIT.
// Source: specs/git-ns/_shared/0.1/git-ns.schema.json

package gitnssharedgitnsv0_1

// ForgeHost The lowercased DNS host of a forge: `github.com`, a GitHub Enterprise Server
// host, `codeberg.org`, or a self-hosted Forgejo instance such as `git.example.org`. No
// scheme, no port, no path. The host is a segment of every resource, so a right never
// crosses forges.
type ForgeHost = string

// Segment One lowercased owner or repository name. Forges compare these
// case-insensitively, so the wire form is always lowercase and a producer lowercases
// before sending. A leading `.` is refused, which rules out `.` and `..`.
type Segment = string

// Resource A forge-qualified resource: `<forge-host>/<owner>` for a namespace, or
// `<forge-host>/<owner>/<repo>` for one repository, all lowercase — `github.com/acme`,
// `github.com/acme/widgets`, `codeberg.org/acme`. The forge is never implied:
// `acme/widgets` alone is not a resource. Containment is by whole segment:
// `github.com/acme` contains `github.com/acme/widgets` and does not contain
// `github.com/acme-labs/x` or `codeberg.org/acme/widgets`.
type Resource = string

// RepoResource A forge-qualified resource naming exactly one repository:
// `<forge-host>/<owner>/<repo>`, lowercase.
type RepoResource = string

// DID A DID, compared by exact string equality.
type DID = string

// NamespaceID The VTC's opaque identifier for a namespace, assigned when it is bound.
// Stable for the life of the binding; never reused for another binding.
type NamespaceID = string

// Right One of the five git rights. Each string is also the TRQP `action` the VTC
// publishes the right under in its Trust Registry, so it is carried verbatim.
// `git.ns.admin` and `git.repo.create` apply to a namespace resource; `git.repo.own` and
// `git.repo.maintain` to a repository resource; `git.commit.sign` to either.
type Right string

// Values Right may take, per this specification's schema.
const (
	RightGitNsAdmin      Right = "git.ns.admin"
	RightGitRepoCreate   Right = "git.repo.create"
	RightGitRepoOwn      Right = "git.repo.own"
	RightGitRepoMaintain Right = "git.repo.maintain"
	RightGitCommitSign   Right = "git.commit.sign"
)

// RepoVisibility Repository visibility on the forge.
type RepoVisibility string

// Values RepoVisibility may take, per this specification's schema.
const (
	RepoVisibilityPublic  RepoVisibility = "public"
	RepoVisibilityPrivate RepoVisibility = "private"
)

// ForgeID An identifier the forge itself assigns — a repository id, a user or
// organisation id — carried as a string so a forge whose ids are not numbers needs no new
// version. GitHub and Forgejo ids are decimal integers written as strings
// (`"812736451"`). Unlike a name, it survives renames and transfers, which is why rights
// and bindings are keyed by it.
type ForgeID = string

// ForgeAccount A person's account on one forge. `id` is authoritative; `login` is for
// display only, because logins can be renamed and re-registered.
type ForgeAccount struct {
	Forge ForgeHost `json:"forge"`
	ID    ForgeID   `json:"id"`

	// The account's current login, as the forge reported it when last seen. Display only.
	Login string `json:"login"`
}

// GitNamespaceKind Whether the owner is an organisation or a personal account, as the
// forge reports it. Present once known: a bridge-mode namespace learns it when binding
// completes, and a manual-mode namespace MAY never learn it.
type GitNamespaceKind string

// Values GitNamespaceKind may take, per this specification's schema.
const (
	GitNamespaceKindOrganization GitNamespaceKind = "organization"
	GitNamespaceKindUser         GitNamespaceKind = "user"
)

// GitNamespaceMode `bridge` — a bridge service acts on the forge for this namespace
// (creates repositories, projects roles, reports drift). `manual` — no automation; people
// with forge access carry out the steps the VTC names, and the VTC governs the rights
// alone.
type GitNamespaceMode string

// Values GitNamespaceMode may take, per this specification's schema.
const (
	GitNamespaceModeBridge GitNamespaceMode = "bridge"
	GitNamespaceModeManual GitNamespaceMode = "manual"
)

// GitNamespaceState `pending` — binding has started and the forge-side proof has not
// arrived yet. `bound` — the VTC governs rights under this namespace.
type GitNamespaceState string

// Values GitNamespaceState may take, per this specification's schema.
const (
	GitNamespaceStatePending GitNamespaceState = "pending"
	GitNamespaceStateBound   GitNamespaceState = "bound"
)

// GitNamespace The VTC's binding to one owner on one forge.
type GitNamespace struct {
	ID    NamespaceID `json:"id"`
	Forge ForgeHost   `json:"forge"`

	// The organisation or user on the forge, lowercased.
	Owner Segment `json:"owner"`

	// Whether the owner is an organisation or a personal account, as the forge reports it.
	// Present once known: a bridge-mode namespace learns it when binding completes, and a
	// manual-mode namespace MAY never learn it.
	Kind *GitNamespaceKind `json:"kind,omitempty"`

	// `bridge` — a bridge service acts on the forge for this namespace (creates repositories,
	// projects roles, reports drift). `manual` — no automation; people with forge access
	// carry out the steps the VTC names, and the VTC governs the rights alone.
	Mode GitNamespaceMode `json:"mode"`

	// `pending` — binding has started and the forge-side proof has not arrived yet. `bound` —
	// the VTC governs rights under this namespace.
	State GitNamespaceState `json:"state"`
}

// Bootstrap Whether each step that turns commit trust on for a repository is in place, as
// last reported. A step that this forge's plan does not need reads `true`.
type Bootstrap struct {
	// The verify-trust check runs on the repository's pull requests — from a workflow
	// committed to it, or, where the forge supports it, required on it from the namespace's
	// own bridge-managed workflow repository at a pinned commit.
	Workflow bool `json:"workflow"`

	// The exempt platform keyring for forge-signed merge commits is committed, or the forge's
	// plan does not need one.
	Keyring bool `json:"keyring"`

	// The repository names the Trust Registry and this VTC as its trust anchors.
	Variables bool `json:"variables"`

	// The forge refuses to merge into the default branch unless the verify-trust check
	// passes, with no bypass, and a pull request cannot change what that check runs: an
	// organisation-required workflow, code-owner review of workflow files, or protected
	// workflow paths, as the forge allows.
	RequiredCheck bool `json:"requiredCheck"`
}

// DriftItemType `roleAdded` — someone holds a forge role the projection does not give
// them. `roleRemoved` — a projected role is missing. `roleChanged` — a projected role is
// present at another level. `requiredCheckMissing` — the verify-trust check is no longer
// required. `protectionWeakened` — branch protection or a ruleset is weaker than the
// projection in another way (force-push allowed, bypass actors added). `bootstrapMissing`
// — a bootstrap file or variable is gone.
type DriftItemType string

// Values DriftItemType may take, per this specification's schema.
const (
	DriftItemTypeRoleAdded            DriftItemType = "roleAdded"
	DriftItemTypeRoleRemoved          DriftItemType = "roleRemoved"
	DriftItemTypeRoleChanged          DriftItemType = "roleChanged"
	DriftItemTypeRequiredCheckMissing DriftItemType = "requiredCheckMissing"
	DriftItemTypeProtectionWeakened   DriftItemType = "protectionWeakened"
	DriftItemTypeBootstrapMissing     DriftItemType = "bootstrapMissing"
)

// DriftItem One difference between the forge's observed state and the VTC's projection of
// a repository.
type DriftItem struct {
	// `roleAdded` — someone holds a forge role the projection does not give them.
	// `roleRemoved` — a projected role is missing. `roleChanged` — a projected role is
	// present at another level. `requiredCheckMissing` — the verify-trust check is no longer
	// required. `protectionWeakened` — branch protection or a ruleset is weaker than the
	// projection in another way (force-push allowed, bypass actors added). `bootstrapMissing`
	// — a bootstrap file or variable is gone.
	Type     DriftItemType `json:"type"`
	Resource RepoResource  `json:"resource"`

	// Whose role differs, for the three role types.
	Account *ForgeAccount `json:"account,omitempty"`

	// What the forge shows, in the forge's own vocabulary (a role name such as `maintain`, a
	// setting name). Absent when nothing is there.
	Observed *string `json:"observed,omitempty"`

	// What the projection calls for, in the forge's own vocabulary. Absent when the
	// projection calls for nothing.
	Expected *string `json:"expected,omitempty"`
}

// SyncState `inSync` — the last comparison found no drift. `drift` — it found some,
// listed in `drift`. `pending` — a change has been sent to the forge and not yet
// confirmed. `unchecked` — nothing compares this repository (a manual-mode namespace).
type SyncState string

// Values SyncState may take, per this specification's schema.
const (
	SyncStateInSync    SyncState = "inSync"
	SyncStateDrift     SyncState = "drift"
	SyncStatePending   SyncState = "pending"
	SyncStateUnchecked SyncState = "unchecked"
)

// Sync How the forge compares with the VTC's projection for one repository.
type Sync struct {
	// `inSync` — the last comparison found no drift. `drift` — it found some, listed in
	// `drift`. `pending` — a change has been sent to the forge and not yet confirmed.
	// `unchecked` — nothing compares this repository (a manual-mode namespace).
	State SyncState `json:"state"`

	// When the forge was last compared. Absent if never.
	CheckedAt *string `json:"checkedAt,omitempty"`

	// Outstanding drift. Empty unless `state` is `drift`.
	Drift []DriftItem `json:"drift"`
}

// RepoSummaryState `pendingCreate` — the name is reserved and the repository is not yet
// confirmed on the forge. `active` — managed. `archived` — archived through
// git-ns/repo/archive; commit rights on it are revoked. `detached` — no longer governed:
// its namespace was unbound, or it moved outside the namespace. `orphaned` — its last
// owner left the community and ownership passed to the namespace admins, who have not yet
// named a new owner. `unmanaged` — it exists on the forge inside a bound namespace but
// was never created or adopted through the VTC.
type RepoSummaryState string

// Values RepoSummaryState may take, per this specification's schema.
const (
	RepoSummaryStatePendingCreate RepoSummaryState = "pendingCreate"
	RepoSummaryStateActive        RepoSummaryState = "active"
	RepoSummaryStateArchived      RepoSummaryState = "archived"
	RepoSummaryStateDetached      RepoSummaryState = "detached"
	RepoSummaryStateOrphaned      RepoSummaryState = "orphaned"
	RepoSummaryStateUnmanaged     RepoSummaryState = "unmanaged"
)

// RepoSummary One repository as the VTC records it.
type RepoSummary struct {
	Resource RepoResource `json:"resource"`

	// The forge's repository id. Absent until the forge has confirmed the repository exists
	// (a `pendingCreate` repository, or one adopted in bridge mode before the first
	// inspection).
	ForgeID    *ForgeID       `json:"forgeId,omitempty"`
	Visibility RepoVisibility `json:"visibility"`

	// `pendingCreate` — the name is reserved and the repository is not yet confirmed on the
	// forge. `active` — managed. `archived` — archived through git-ns/repo/archive; commit
	// rights on it are revoked. `detached` — no longer governed: its namespace was unbound,
	// or it moved outside the namespace. `orphaned` — its last owner left the community and
	// ownership passed to the namespace admins, who have not yet named a new owner.
	// `unmanaged` — it exists on the forge inside a bound namespace but was never created or
	// adopted through the VTC.
	State RepoSummaryState `json:"state"`

	// The DIDs holding `git.repo.own` on this repository by an explicit grant. Empty only for
	// an `unmanaged` repository, and for an `orphaned` one whose ownership rests with the
	// namespace admins by implication.
	Owners    []DID     `json:"owners"`
	Bootstrap Bootstrap `json:"bootstrap"`
	Sync      Sync      `json:"sync"`
}

// RightRecord One recorded right. Implied rights (§4.2 of the rights model: `own` implies
// `maintain` implies `commit.sign` on the same resource; `ns.admin` implies `repo.create`
// and `own` across its namespace) are not records and never appear as RightRecords.
type RightRecord struct {
	// Who holds the right. For `git.commit.sign` this is the DID whose commit signatures the
	// CI check accepts.
	Subject  DID      `json:"subject"`
	Right    Right    `json:"right"`
	Resource Resource `json:"resource"`

	// The actor whose task caused the right: the granter, the creator of a repository (for
	// its first `own`), the adopting admin, the transferring owner, or the binding admin (for
	// the first `git.ns.admin`). The VTC's own DID for a right it derives from its
	// configuration.
	GrantedBy DID    `json:"grantedBy"`
	GrantedAt string `json:"grantedAt"`

	// When the right lapses. Absent: no expiry.
	ExpiresAt *string `json:"expiresAt,omitempty"`

	// The granter's free-text reason. Disclosed only to holders of `git.repo.own` on the
	// resource and of `git.ns.admin` over it.
	Reason *string `json:"reason,omitempty"`
}
