[workspace]
resolver = "2"
members = [
    "trust-tasks-rs",
    "trust-tasks-codegen",
    "trust-tasks-https",
    "trust-tasks-proof",
    "trust-tasks-didcomm",
    "trust-tasks-tsp",
    "trust-tasks-capability-client",
]

[workspace.package]
edition = "2021"
rust-version = "1.95"
license = "Apache-2.0"
repository = "https://github.com/trustoverip/dtgwg-trust-tasks-tf"
