//! Generated by `trust-tasks-codegen` — do not edit by hand.
//!
//! Round-trip tests harvested from the spec's `spec.md`, plus a
//! `rejects_invalid_examples` test for any fixtures in
//! `payload.invalid-examples.json` (validate feature), for
//! `did-management/did/list/0.1`
#[allow(unused_imports)]
use trust_tasks_rs::specs::did_management::did::list::v0_1 as spec;
#[test]
fn request_example_1() {
    const JSON: &str = "{\n  \"id\": \"list-req-1\",\n  \"type\": \"https://trusttasks.org/spec/did-management/did/list/0.1\",\n  \"issuer\": \"did:key:z6MkAlice\",\n  \"recipient\": \"did:web:did.example.com\",\n  \"issuedAt\": \"2026-06-01T12:00:00Z\",\n  \"payload\": { \"limit\": 50, \"domain\": \"did.example.com\" }\n}\n";
    let doc: trust_tasks_rs::TrustTask<spec::Payload> =
        serde_json::from_str(JSON).expect("deserialize request example");
    let rendered = serde_json::to_value(&doc).expect("re-serialize");
    let expected: serde_json::Value = serde_json::from_str(JSON).expect("re-parse expected");
    assert_eq!(rendered, expected, "request example failed round-trip");
}
#[test]
fn response_example_1() {
    const JSON: &str = "{\n  \"id\": \"list-resp-1\",\n  \"type\": \"https://trusttasks.org/spec/did-management/did/list/0.1#response\",\n  \"threadId\": \"list-req-1\",\n  \"issuer\": \"did:web:did.example.com\",\n  \"recipient\": \"did:key:z6MkAlice\",\n  \"issuedAt\": \"2026-06-01T12:00:01Z\",\n  \"payload\": {\n    \"records\": [{\n      \"mnemonic\": \"alice\", \"owner\": \"did:key:z6MkAlice\",\n      \"createdAt\": \"2026-06-01T10:00:00Z\", \"updatedAt\": \"2026-06-01T10:05:01Z\",\n      \"versionCount\": 1, \"method\": \"webvh\", \"domain\": \"did.example.com\", \"disabled\": false\n    }],\n    \"total\": 1\n  }\n}\n";
    let doc: trust_tasks_rs::TrustTask<spec::Response> =
        serde_json::from_str(JSON).expect("deserialize response example");
    let rendered = serde_json::to_value(&doc).expect("re-serialize");
    let expected: serde_json::Value = serde_json::from_str(JSON).expect("re-parse expected");
    assert_eq!(rendered, expected, "response example failed round-trip");
}
/// Each fixture in `payload.invalid-examples.json` MUST be
/// rejected by at least one of: serde deserialization, or
/// JSON-Schema validation under the `validate` feature. The
/// fixture file documents the producer-side bug class that
/// each payload exemplifies; this generated test pins it.
#[cfg(feature = "validate")]
#[test]
fn rejects_invalid_examples() {
    use trust_tasks_rs::validate::ValidatedPayload;
    let fixtures: &[(&str, &str)] = &[
        ("Negative limit.", "{\n  \"limit\": -1\n}"),
        ("limit above max.", "{\n  \"limit\": 5000\n}"),
    ];
    for (i, (note, raw)) in fixtures.iter().enumerate() {
        let value: serde_json::Value = match serde_json::from_str(raw) {
            Ok(v) => v,
            Err(_) => continue,
        };
        let serde_ok = serde_json::from_value::<spec::Payload>(value.clone()).is_ok();
        let schema_ok = spec::Payload::validate_value(&value).is_ok();
        assert!(
            !(serde_ok && schema_ok),
            "invalid-example #{} ({:?}) was accepted by both serde and JSON Schema; \
                         the fixture's stated failure class is no longer caught:\n{}",
            i + 1,
            note,
            raw
        );
    }
}
