// Code generated by scripts/build-go-bindings.mjs. DO NOT EDIT.
// Source: specs/vta/memory/put/0.1/payload.schema.json

package vtamemoryputv0_1

import (
	"encoding/json"
	"github.com/trustoverip/dtgwg-trust-tasks-tf/trust-tasks-go/trusttasks"
)

// Response Success response to vta/memory/put. Type
// https://trusttasks.org/spec/vta/memory/put/0.1#response.
type Response struct {
	// The stored item's key.
	Key string `json:"key"`
	Ext *Ext   `json:"ext,omitempty"`
}

// Ext Vendor-namespaced extension object per SPEC.md §4.5.1. Each immediate key MUST be a
// reverse-DNS namespace; structure under each namespace is opaque to the framework.
type Ext = map[string]json.RawMessage

// Payload VTA Memory Put — payload
type Payload struct {
	// The VTA context the memory item is scoped to (the isolation boundary).
	ContextID string `json:"contextId"`

	// Agent-chosen identifier for the item; re-putting the same key upserts.
	Key string `json:"key"`

	// Opaque memory text (a fact, summary, or preference).
	Value string `json:"value"`

	// Ecosystem-defined extension members per SPEC.md §4.5.1.
	Ext *Ext `json:"ext,omitempty"`
}

// TypeURI is the Trust Task type URI this package's Payload is carried under.
const TypeURI = "https://trusttasks.org/spec/vta/memory/put/0.1"

// ResponseTypeURI is the success-response form of TypeURI (SPEC §4.4.1).
const ResponseTypeURI = "https://trusttasks.org/spec/vta/memory/put/0.1#response"

// PayloadSchemaJSON is this specification's payload schema, as JSON text.
//
// SPEC §7.2 item 2 is performed against this. It ships with the package rather
// than only as a file under specs/ because a Go struct carries none of the
// schema's constraints — not minLength, not pattern, not the oneOf mutual
// exclusion — so without it every such rule is unenforced. Cross-file $refs are
// already inlined, so it needs no resolver.
const PayloadSchemaJSON = "{\"$schema\":\"https://json-schema.org/draft/2020-12/schema\",\"$id\":\"https://trusttasks.org/spec/vta/memory/put/0.1\",\"title\":\"VTA Memory Put — payload\",\"type\":\"object\",\"additionalProperties\":false,\"required\":[\"contextId\",\"key\",\"value\"],\"properties\":{\"contextId\":{\"type\":\"string\",\"description\":\"The VTA context the memory item is scoped to (the isolation boundary).\"},\"key\":{\"type\":\"string\",\"description\":\"Agent-chosen identifier for the item; re-putting the same key upserts.\"},\"value\":{\"type\":\"string\",\"description\":\"Opaque memory text (a fact, summary, or preference).\"},\"ext\":{\"$ref\":\"#/$defs/Ext\",\"description\":\"Ecosystem-defined extension members per SPEC.md §4.5.1.\"}},\"$defs\":{\"Response\":{\"$anchor\":\"response\",\"title\":\"VTA Memory Put — response payload\",\"description\":\"Success response to vta/memory/put. Type https://trusttasks.org/spec/vta/memory/put/0.1#response.\",\"type\":\"object\",\"additionalProperties\":false,\"required\":[\"key\"],\"properties\":{\"key\":{\"type\":\"string\",\"description\":\"The stored item's key.\"},\"ext\":{\"$ref\":\"#/$defs/Ext\"}}},\"Ext\":{\"title\":\"Ext\",\"description\":\"Vendor-namespaced extension object per SPEC.md §4.5.1. Each immediate key MUST be a reverse-DNS namespace; structure under each namespace is opaque to the framework.\",\"type\":\"object\",\"minProperties\":1,\"additionalProperties\":true,\"propertyNames\":{\"pattern\":\"^[a-z][a-z0-9-]*(\\\\.[a-z0-9-]+)+$\"}}}}"

// ResponsePayloadSchemaJSON is PayloadSchemaJSON for the success-response variant.
const ResponsePayloadSchemaJSON = "{\"$schema\":\"https://json-schema.org/draft/2020-12/schema\",\"$ref\":\"#/$defs/Response\",\"$defs\":{\"Response\":{\"$anchor\":\"response\",\"title\":\"VTA Memory Put — response payload\",\"description\":\"Success response to vta/memory/put. Type https://trusttasks.org/spec/vta/memory/put/0.1#response.\",\"type\":\"object\",\"additionalProperties\":false,\"required\":[\"key\"],\"properties\":{\"key\":{\"type\":\"string\",\"description\":\"The stored item's key.\"},\"ext\":{\"$ref\":\"#/$defs/Ext\"}}},\"Ext\":{\"title\":\"Ext\",\"description\":\"Vendor-namespaced extension object per SPEC.md §4.5.1. Each immediate key MUST be a reverse-DNS namespace; structure under each namespace is opaque to the framework.\",\"type\":\"object\",\"minProperties\":1,\"additionalProperties\":true,\"propertyNames\":{\"pattern\":\"^[a-z][a-z0-9-]*(\\\\.[a-z0-9-]+)+$\"}}}}"

// Spec is the SPEC §7.2 policy for the request variant, taken from this
// specification's front matter. Pass it to trusttasks.ConsumeInbound — items 5b,
// 7 and 8 are per-specification and cannot be derived from the document alone,
// and item 2 needs the schema it carries.
var Spec = trusttasks.SpecPolicy{
	TypeURI:             TypeURI,
	IsBearer:            false,
	IsProofRequired:     true,
	IsRecipientRequired: true,
	IsIssuedAtRequired:  true,
	PayloadSchema:       PayloadSchemaJSON,
}

// ResponseSpec is the SPEC §7.2 policy for the success-response variant.
// IsRecipientRequired tracks the *issuer* party's requirement, because a response
// swaps the parties (§7.3 item 5).
var ResponseSpec = trusttasks.SpecPolicy{
	TypeURI:             ResponseTypeURI,
	IsBearer:            false,
	IsProofRequired:     true,
	IsRecipientRequired: true,
	IsIssuedAtRequired:  true,
	PayloadSchema:       ResponsePayloadSchemaJSON,
}
